### ISSUE TITLE
Is Debian Buster Supported?

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-pipeline-library#30] opened 2020-12-16 23:23 UTC
Your [meta/main.yml](https://github.com/wcm-io-devops/ansible-jenkins-pipeline-library/blob/master/meta/main.yml#L13) only indicates support for Debian Stretch. I had been using this meta role successfully for months with Debian Buster 10.5 machines. [I've recently run into some problems with this role](https://github.com/wcm-io-devops/ansible-jenkins-pipeline-library/issues/29), which may or may not be related to this, and was wondering if you knew of any reasons why this meta roles shouldn't work fine on Debian Buster as well as Stretch.

**Comment by tobias-richter** [comment] 2021-01-19 14:28
@timblaktu I can confirm that buster is supported. We are not doing anything special for stretch or buster.
I have updated the meta information. Since https://github.com/wcm-io-devops/ansible-jenkins-pipeline-library/issues/29 is closed I will also close this issue since I assume that the problems are fixed.

**Closed as completed by tobias-richter** 2021-01-19 14:28 UTC
